project:
  type: website
  output-dir: ../hessen

website:
  title: "2023 Election Dashboard Hessen {{< iconify openmoji flag-poland rotate=180deg >}}"
  navbar:
    left:
      - href: index.qmd
        text: Spending
      - targeting.qmd
      - href: about.qmd
        text: About
      - text: "Bayern LTW {{< iconify openmoji bavaria-flag >}}"
        href: "https://favstats.github.io/BayernHessenLTW2023/bayern/"
    right:
      - icon: github
        href: https://github.com/favstats
      - icon: twitter
        href: https://twitter.com/favstats
  sidebar: true  
format:
  html:
    theme: litera
    
