project:
  type: website
  output-dir: ../bayern

website:
  title: "2023 Election Dashboard Bayern {{< iconify openmoji bavaria-flag >}}"
  navbar:
    left:
      - href: index.qmd
        text: Spending
      - targeting.qmd
      - href: about.qmd
        text: About
      - text: "Hessen LTW {{< iconify openmoji flag-poland rotate=180deg >}} "
        href: "https://favstats.github.io/LTW2023/hessen/"
    right:
      - icon: github
        href: https://github.com/favstats
      - icon: twitter
        href: https://twitter.com/favstats
    
format:
  html:
    theme: litera
    
